title: "加华移民 JiaHua Immigration"
name: "加华移民 JiaHua Immigration"
description: "提供加拿大全流程签证、移民项目、职业规划、一站式服务"

url: "https://ykonguo.github.io"
baseurl: "/jiahuamimmigration"

theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

locale: "zh-CN"
permalink: /:categories/:title/

author:
  name: "加华移民 JiaHua Immigration"

markdown: kramdown
highlighter: rouge

# 导航栏
navigation:
  - title: 首页
    url: /

  - title: 签证
    url: /visa/

  - title: 移民项目
    url: /immigration/

  - title: 职业规划
    url: /career/

  - title: 联系我们
    url: /contact/
