title: "加华移民 JiaHua Immigration"
name: "加华移民 JiaHua Immigration"
description: "加拿大签证、移民项目评估、职业规划一站式顾问服务"
locale: "zh-CN"

url: "https://ykonguo.github.io"
baseurl: "/jiahuaiimmigration"  # 如果你的仓库叫 minimal-mistakes 则写 /minimal-mistakes
